rustfs:
  mode:
    distributed:        # 4 pods and 16 pvcs(each pod has 4 pvcs) OR 16 pods and 16 pvcs(each pod has 1 pvc)
      enabled: false
    standalone:         # only one pod and one pvc
      enabled: true
      # existingClaim:
      #   dataClaim:    # use existing pvc claim for data storage
      #   logsClaim:    # use existing pvc claim for logs storage

  replicaCount: 4       # number of cluster nodes

  secret:
    allowInsecureDefaults: false
    existingSecret: rustfs-secret

  ingress:
    enabled: false

  gatewayApi:
    enabled: true
    gatewayClass: traefik
    listeners:
      http:
        name: web
        port: 8000
      https:
        name: websecure
        port: 8443
    hostname: rustfs.lunics.cloud
    existingGateway:
      name:      traefik-gateway
      namespace: traefik

  storageclass:
    name:            local-path
    dataStorageSize: 256Mi
    logStorageSize:  256Mi
    pvcAnnotations:  {}
