keycloak:
  postgresql:
    enabled: true
    auth:
      database: keycloak
      username: keycloak
      existingSecret: keycloak-secret
      secretKeys:
        userPasswordKey: password
  production: false
  hostnameStrict: false
  adminRealm: master
  auth:
    adminUser: user
    # administrator password for the new user
    adminPassword: ""
    # Existing secret containing Keycloak admin password
    existingSecret: keycloak-secret
    # Key where the Keycloak admin password is being stored inside the existing secret
    passwordSecretKey: admin-password
