keycloak:
  image:
    repository: bitnamilegacy/keycloak      # bitnami/keycloak is not free

  postgresql:
    enabled: false
    auth:
      database: keycloak
      username: keycloak
      existingSecret: keycloak-secrets
      secretKeys:
        userPasswordKey: password

  externalDatabase:
    host:     keycloak-postgres-rw.keycloak.svc.cluster.local
    port:     5432
    database: keycloak
    user:     keycloak
    existingSecret:            keycloak-secrets
    existingSecretUserKey:     username
    existingSecretPasswordKey: password

  production: false
  hostnameStrict: false
  adminRealm: master
  auth:
    adminUser: user
    # administrator password for the new user
    adminPassword: ""
    # Existing secret containing Keycloak admin password
    existingSecret: keycloak-secrets
    # Key where the Keycloak admin password is being stored inside the existing secret
    passwordSecretKey: admin-password
