apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name:      rustfs
  namespace: rustfs
spec:
  secretStoreRef:
    name: openbao-secret-store
    kind: ClusterSecretStore
  target:
    name: rustfs-secret
  data:
  - secretKey: RUSTFS_ACCESS_KEY
    remoteRef:
      key: rustfs/access-key
  - secretKey: RUSTFS_SECRET_KEY
    remoteRef:
      key: rustfs/secret-key
