argo-cd:
  fullnameOverride: argo-cd

  configs:
    secret:
      createSecret: false

  global:
    domain: argo-cd.lunics.cloud
  
  server:
    httproute:
      enabled: true
      hostnames:
        - argo-cd.lunics.cloud
      parentRefs:
        - group:       gateway.networking.k8s.io    # required to avoid OutOfSync
          kind:        Gateway
          name:        traefik-gateway
          namespace:   traefik
          sectionName: web
        - group:       gateway.networking.k8s.io
          kind:        Gateway
          name:        traefik-gateway
          namespace:   traefik
          sectionName: websecure
