apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name:      pocket-id-encryption-key
  namespace: pocket-id
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    name: pocket-id
  data:
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: pocket-id/encryption-key
