apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name:      keycloak
  namespace: keycloak
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-secret-store
  target:
    name: keycloak
  data:
    - secretKey: admin-password
      remoteRef:
        key: keycloak/admin-password
    - secretKey: username
      remoteRef:
        key: keycloak/postgres-owner-name
    - secretKey: password
      remoteRef:
        key: keycloak/postgres-owner-password
